### PR TITLE
Dropbear stop

### PR DESCRIPTION
**Pull request by nielsranosch**
Hey!
Thank you for this cool guide, it will come in handy when I change DSL providers.
Maybe dropbear shouldn't run indefinetely; I'd prefer it if it were to terminate after 10 minutes. Would the code change accomplish that?

I have some more questions and e-mailed you. Hope you find the time :-)

### CODE REVIEW

**Comment by majuss** [comment]
I don't see a reason why dropbear should be killed?! As long as you don't forward the ssh port nobody can attack you via ssh.

**Comment by nielsranosch** [comment]
It might be more convenient for the setting I want to use it in. I am also considering turning off the webinterface.

But you're right, for most people this change wouldn't make sense and probably cause confusion.

**Comment by majuss** [comment]
I also thought about a minimal setup, with disabled buttons, lcd etc. (I already uninstalled them physically but the processes are still running). Please keep me up to date with your progress :)

**Comment by T-E-N** [comment]
> I also thought about a minimal setup, with disabled buttons, lcd etc.

https://forum.openwrt.org/viewtopic.php?pid=364433#p364433 and the preceding page on lcd4linux seems to have come up with something in this regard.

Showing line&load parameters (my 904 reports CPU 100% OOTB) might put the display to better use though.

**Pull request closed without merging**
